# Generated by Django 4.2.2 on 2023-06-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserConnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("subject", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=255)),
            ],
        ),
    ]
