# Generated by Django 4.2.2 on 2023-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("images", models.FileField(upload_to="OurTeams/")),
                ("position", models.CharField(max_length=255)),
                ("discription", models.CharField(max_length=255)),
                ("facebook", models.CharField(max_length=255)),
                ("twitter", models.CharField(max_length=255)),
                ("instagram", models.CharField(max_length=255)),
                ("linkedin", models.CharField(max_length=255)),
            ],
        ),
    ]
