# Generated by Django 4.2.2 on 2023-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_ourteams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourteams",
            name="images",
            field=models.FileField(upload_to="\\static\\images\\OurTeamsImages/"),
        ),
    ]
