# Generated by Django 4.2.2 on 2023-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourteams",
            name="images",
            field=models.FileField(upload_to=""),
        ),
    ]
