# Generated by Django 4.2.2 on 2023-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_alter_ourteams_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuwaveDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.CharField(max_length=255)),
                ("twitter", models.CharField(max_length=255)),
                ("instagram", models.CharField(max_length=255)),
                ("linkedin", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("address", models.CharField(max_length=255)),
            ],
        ),
    ]
