# Generated by Django 4.2.2 on 2023-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_auwavedetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="auwavedetails",
            name="Discription",
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auwavedetails",
            name="email",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
